# Generated by Django 4.2 on 2023-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя: ')),
                ('age', models.IntegerField(max_length=20, verbose_name='Возраст: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('poll', models.CharField(choices=[('m', 'мужской'), ('w', 'женский')], max_length=1, verbose_name='Ваш пол: ')),
            ],
        ),
    ]
