# Generated by Django 4.2 on 2023-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0005_news_user_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='images/news', verbose_name='Картинка'),
        ),
    ]
